### ISSUE TITLE
Root path space views

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#1060]
As requested by @nikolausWest, we want to be able to omit the leading `world/` in our example paths.

For instance, a user can log to the paths
```
image
detections
text_logging
```

And then the viewer will automatically create two spaceviews:
* One called "2D" containing `image` and `detections`
* One called "text_logging"

### Upside
Users can care less about what they log. Log to `image` and `detections`, and you can still overlay the detections on the image.

### Downside
We encourage a less structured way to organize your entities.

### TODO
A few steps to reach that in a nice way:

* [x] Allow making the root (`/`) a space view
* [x] Name space views based on last component name plus category (`world/camera/video` -> `video 2D`)
* [ ] Split `ViewCategory` into `ViewCategory2D` and `ViewCategory3D`
* [x] Make sure we do the correct things with all the transform stuff everywhere
