### ISSUE TITLE
Minor Python SDK cleanup tracking issue

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#1753]
* [x] https://github.com/rerun-io/rerun/issues/1583
* [x] https://github.com/rerun-io/rerun/issues/1701
* [x] https://github.com/rerun-io/rerun/pull/1740
* [ ] Inconsistencies in API argument types
* [ ] Some primitives have `labels`, other don't

**Comment by emilk** [comment]
This is mostly fixed with 0.9
