### ISSUE TITLE
Tracking issue: Reduce friction in adding documentation

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#1754]
Adding documentation is currently quite painful. We'd like to make it simpler by:
- Making images/screenshots easier to create and store outside of Git
- Bringing the content of documentation into this repository (it is currently under [rerun-io/rerun-docs](https://github.com/rerun-io/rerun-docs))
- Adding support for docs previews for pull requests

---

- [x] https://github.com/rerun-io/rerun/issues/2132
- [x] https://github.com/rerun-io/rerun/issues/2133
- [x] https://github.com/rerun-io/rerun/issues/2134
- [x] https://github.com/rerun-io/rerun/issues/2135
- [x] https://github.com/rerun-io/rerun/issues/2136
