### ISSUE TITLE
Jupyter Improvements

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1815]
Tracking issue for some assorted fixes beyond the current Jupyter MVP:
 - [ ] https://github.com/rerun-io/rerun/issues/1808
 - [ ] Each cell should ideally have a unique, but stable, application-id. Unfortunately jupyter does not directly have access the cell-id metadata.
 - [ ] Investigate introducing a "RecordingHandle" to the Python SDK to simplify some of the global-context/state pieces. The handle would expose all the existing python APIs and eventually allow creation of a blueprint which would return a jupyter-renderable object.
    ```
    rh = rr.start_recording()
    rh.log_image(...)
    rh.log_points(...)
    rh.blueprint().view('img/')
    ```
    The existing rr APIs would just pass through to the default recording handle.
  - [ ] Long-term optionally move rerun from iFrame back to a single instance controlling multiple canvases. This would allow us to have multiple views (from different blueprints) on top of the same data without the need to duplicate memory.

**Comment by jprochazk** [comment]
@jleibs What's the status of this after the recent notebook changes? It's linked from our docs, and I'm not sure how the roadmap has changed since over a year ago.

**Comment by aedm** [comment]
This roadmap is substantially realized and can be closed.

The notebook stack now covers every enumerated goal: `rerun.notebook.Viewer` (a real viewer object you stream into), a blueprint builder API (`Viewer(blueprint=…)` / `set_application_blueprint`), an ipywidgets port (the `rerun_notebook` anywidget package), incremental live-streaming (`bindings.set_callback_sink`), and a loading state (`_render_loading_html` + spinner). It landed in 0.17.0 (PR #6573/#6640) and has matured significantly since (event callbacks, `set_time_ctrl`, `send_table`).

Verified on 0.33.0 — all roadmap integration points present. Any still-aspirational sub-bullets are best tracked in a fresh scoped issue.
