### ISSUE TITLE
Minimal control of views through SDK

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1889]
The long-term goal for controlling the UI is introduction of a blueprint store for most UI state: https://github.com/rerun-io/rerun/blob/main/design/blueprint_store.md

However, we can create immediate value for users (in particular in a notebook context) with just a subset of the functionality from the RFC.

In order of priority:
 - [x] Specify panel state (collapsed or expanded)  for the 3 panels
 - [ ] ~~Specify selected timeline~~
 - [x] Specify whether to enable auto-view creation (this should be one of the first things logged; probably part of init?)
 - [x] Specify views to be created (view name, space root, and list of entity paths)
 - [ ] ~~Specify entity properties~~
   - Split out to: https://github.com/rerun-io/rerun/issues/5519

Notably this does *not* try to tackle:
 - View Layout
 - Data queries / filters
 - Data-overrides / defaults

Proposed API:
```python
# Trivial
rr.view.Spatial2D(origin="world/camera")

# Implies
rr.view.Spatial2D(origin="world/camera", contents="$origin/**")

EntityPathExpressionLike: (str, Sequence[str], EntityPathExpression)
Spatial2D(origin: str, contents: EntityPathExpressoinLike = "$origin/**")

# Which is syntactic sugar for:
entities = rr.view.EntityPathExpression("$origin/**")
rr.view.Spatial2D(origin="world/camera", contents=entities)

# With extra data
rr.view.Spatial2D(origin="world/camera", contents="+$origin/** +/world/points")

# Or for python formatter clarity, allow lists:
rr.view.Spatial2D(
    origin="world/camera",
    contents=[
        "+$origin/**",
        "+/",
    ],
)
```

**Comment by emilk** [comment]
Let's get started on the design of this ASAP

**Comment by jleibs** [comment]
Done in:
 - https://github.com/rerun-io/rerun/pull/5408
 - https://github.com/rerun-io/rerun/pull/5484
 - https://github.com/rerun-io/rerun/pull/5498
