### ISSUE TITLE
Upgrade example documentation

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#2266]
Many people learn best from studying examples, but our documentation around our examples is currently sub-par. We need to make it much easier to find the most helpful example and make the documentation easier to maintain.

Roughly prioritized high to low:

- [x] Make the landing of https://www.rerun.io/examples more interesting (screenshots, links, or just land on https://www.rerun.io/examples/real-data)
- [x] Make the written content and structure of the examples page more compelling
- [ ] #2928
- [x] #2259 
- [x] #2267
- [x] #2268
- [x] #2270
- [ ] #2272
- [x] https://github.com/rerun-io/rerun/issues/2117
- [x] Unify screenshots in docs
- [x] #2273
- [x] #2399
- [ ] Make it easier to find the API docs for Python and Rust
- [x] https://github.com/rerun-io/rerun/issues/2313
- [x] All example screenshots should have alt-texts
- [ ] Docs site shows what rerun api's are used in each example
- [ ] Examples docs shows live web viewer where possible

**Comment by emilk** [comment]
It's high priority to work on these issues, but not high priority to close every single on of them. Let's start with the low hanging fruit

**Comment by nikolausWest** [comment]
Closing this issue and moving the remaining pieces we want to do to to a new tracking issue
