### ISSUE TITLE
C++ SDK

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#2516]
This is the tracking issue for our initial high-level C++ SDK

### Goals
* High-level API
* Easy to use
* Easy to install
* For developers on their own machines

### Non-goals
* C
* Embedded machines
* Header-only

We will save this for later.

### Low-level C SDK
We wrap our Rust SDK with a minimal set of functions for:

* `init`
* `connect`, `save`
* `log` a `DataRow`

The Rust side is responsible for:
* Batching
* TCP communication
* Streaming logs to disk

### Low-level C++ SDK
Basically a C++-friendly wrapper around the C SDK

### Code-generated classes
* https://github.com/rerun-io/rerun/issues/2647

We use `re_types` (#2241) to generate classes for datatypes, components, and archetypes.

These are converted to Arrow-messages using the official Arrow C++ SDK.

### Integrations
Finally, we have opt-in integrations with various libraries such as:
* OpenCV
* Eigen
* …

## Distribution
The C SDK will consist of a single `rerun.h` header, and then a dynamic and/or static library of the `rerun_c` crate.

The C++ SDK will have a CMakelists.txt for ease of use in cmake build systems. We can maybe set up a system where cmake downloads and install the Rerun C++ SDK for users, including dependencies (Arrow).

## TODO
* [ ] https://github.com/rerun-io/rerun/issues/2647
* [x] https://github.com/rerun-io/rerun/issues/2662
* [x] #2797
* [ ] #2798
* [x] What C++ version to target
   * The Arrow C++ SDK requires C++17, but that should only affect the version for building our C++ SDK binaries
* [x] Figure out the API
* [ ] Generate API docs
* [ ] High level examples
* [ ] Write high-level C++ docs
* [x] Write C++ examples
* [ ] Library distribution
* …

**Comment by Wumpf** [comment]
Discussed today in the standup the many perils of shipping C++ binaries. Since we depend on Arrow C++ SDK right now, any source distribution would enforce C++17. We came up with various solutions (use Arrow C library, build out C SDK and forward to that, isolate Arrow code behind a C interface, etc. etc.) but concluded that this is very low priority for us right now: It seems that all known early adopters are (while reportedly not _using_ C++17) are on compiler versions that *supports* C++17. So as long as our interface isn't C++17 requiring, our implementations can despite shipping as source.
