### ISSUE TITLE
Make Rerun easy to learn directly from the viewer

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#2695]
## Goal
Just typing
```bash
pip install rerun-sdk
rerun
```
Should be an amazing entrypoint into learning about what Rerun is, how to use it, and gaining a productive mental model of how things fit together. Using the Rerun viewer should naturally teach you what you need without requiring you to read through documentation (although it might point you to documentation for learning more about something).

We'll achieve this both by including explanations, product tours, and examples right in the app, but also by making sure the design is consistent with the underlying data model such that using it naturaly builds useful intuition.

## Roadmap
- [x] #2696
- [x] #2298
- [x] #2697
- [x] #2652
- [x] #2513
- [x] #2701
- [x] #769
- [x] #2118
- [x] #404 
- [x] https://github.com/rerun-io/rerun/issues/3096
- [x] #2699
- [ ] Transform graph view
- [ ] Export blueprint as code
