### ISSUE TITLE
Use consistent writing style for UI labels

### ISSUE THREAD

**Issue by martenbjork** [rerun-io/rerun#2724]
The casing of the text strings in the UI is currently all over the place. Examples:

- `Visible history` (sentence case)
- `in Space View:` (initial lowercase, then Title Case, ending with colon)
- `colorrgba` (lowercase)
- `Spatial` (initial uppercase)
- `camera` (lowercase)
- `Entity:` (ending with colon)
- `structure_from_motion` (snake_case)
- `No future selections found` (no ending period)
- `Add new Space View.` (ending period)

We should add some writing rules and then start fixing these issues.

## Writing rules (WIP)
1. If the text string references a coding convention, use the casing that respects the coding convention. E.g. `COLMAP`,  `translate3d` or `InstanceMethod`.
2. Default to `Sentence case like this` for most elements in the UI
3. Rerun concepts are Title Cased. E.g. `Space View`, `Selection View`, `Command Palette`,  `Memory Panel`.
5. Only end sentences with a period when there are multiple sentences in the current context. For instance, if a tooltip contains two sentences, both should end with a period. 
6. Never use colons `:` when labeling a UI field

## Todo list (keep adding to it if anything breaks the rules above)
- [ ] Remove the colon after the label 
<img width="301" alt="image" src="https://github.com/rerun-io/rerun/assets/875708/bf59a543-983d-4b8b-81fe-6974e3eac850">

- [ ] Remove the colon after the label 
<img width="254" alt="image" src="https://github.com/rerun-io/rerun/assets/875708/34957ca9-458e-405f-a30b-1fe02336d764">

- [ ] Remove the period at the end of the tooltip sentence
<img width="363" alt="image" src="https://github.com/rerun-io/rerun/assets/875708/b3cb70b9-d74a-459d-8f2b-33ce66b33f33">

- [ ] Remove the period at the end of the tooltip sentence
<img width="150" alt="image" src="https://github.com/rerun-io/rerun/assets/875708/7ca1414c-4bf9-4e90-bf29-54a248049491">

- [ ] Remove the colon after the label
<img width="159" alt="image" src="https://github.com/rerun-io/rerun/assets/875708/a7c54655-68b1-4758-92e9-30d8f53ef5ec">

- [ ] Remove the period at the end of the sentence
<img width="559" alt="image" src="https://github.com/rerun-io/rerun/assets/875708/f7544067-edc5-40bb-8af0-e066b3357807">

- [x] Remove the period at the end of the sentence 
<img width="422" alt="image" src="https://github.com/rerun-io/rerun/assets/875708/49911853-91e1-431b-a61c-a531974f6507">

- [x] Remove the period at the end of the sentence
<img width="130" alt="image" src="https://github.com/rerun-io/rerun/assets/875708/8df398ab-563e-4394-8403-09f8871a6b98">

- [x] Change to sentence case (`Frames per second`)
<img width="150" alt="image" src="https://github.com/rerun-io/rerun/assets/875708/4d902c31-3023-4a4b-8f04-9ec79995c58d">

- [x] Remove period at the end of this sentence:
<img width="331" alt="image" src="https://github.com/rerun-io/rerun/assets/875708/3d800a85-a0b8-4215-99eb-1de17d88a549">

- [x] Uppercase all instances of Rerun concepts
`Viewer`, `Memory Panel`, `Command Palette`, Blueprints View`, `Selection View`, `Timeline View` etc.

**Comment by abey79** [comment]
@martenbjork how do you feel about case in this particular case?
<img width="256" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/a4215b04-ee51-4f1f-a014-f90d94864079">

"In Space View"?

**Comment by martenbjork** [comment]
> "In Space View"?

I think it should be just like this. Uppercase `In` since it's a sentence and title case `Space View` since it's a concept.
