### ISSUE TITLE
Improve styling of demo header

### ISSUE THREAD

**Issue by martenbjork** [rerun-io/rerun#2732]
<img width="814" alt="image" src="https://github.com/rerun-io/rerun/assets/875708/fad8fc9e-b94e-4d3a-b0a1-2ebf411e7778">

## TODO
- [ ] Add [CSS font smoothing](https://ui.dev/rwd/articles/font-smoothing) to all top bar elements to better match the appearance of the text that is rendered in the OS / in Rust
- [ ] For now, change the color to match the Rerun menu (#262626)
- [ ] Change the text color of all elements to `#cad8de`
- [ ] Change the color of the Github logo to match
- [ ] Change the font size of the drop down label to 14px
- [ ] Change the font size of individual drop down items to 12px
- [ ] Change the hover state of the `?` icon to match the radius and size of the "view toggles" in the upper right corner
- [ ] https://github.com/rerun-io/rerun/issues/2856
- [ ] For the `?` tooltip, reduce the font size to `14px`. Set the line height to `1.33`. Set letter spacing to `0`. Set the spacing between paragraphs to `8px`. Remove the underline behind links. 
<img width="323" alt="image" src="https://github.com/rerun-io/rerun/assets/875708/adf4a32d-8183-4414-9d48-4ac62877bad0">
