### ISSUE TITLE
Improve design of text inputs

### ISSUE THREAD

**Issue by martenbjork** [rerun-io/rerun#2735]
## Current implementation

<img width="291" alt="image" src="https://github.com/rerun-io/rerun/assets/875708/db9035a4-9a87-4f9b-836f-bbb9a002574b">

## Design system implementation 👉[Figma](https://www.figma.com/file/3WX8yUqa8ECmhLwV6NIF3a/Rerun-Design-System?type=design&node-id=1252-15702&mode=design&t=UEwrIbrfSM5Yz0sP-0)

<img width="830" alt="image" src="https://github.com/rerun-io/rerun/assets/875708/bdff8891-dc7e-4729-aead-db35c682bcbe">

## Todo
- [ ] Change default state to look like the design above
- [ ] Change the hover state to look like the design above
- [ ] Change the focus state to look like the design above

**Comment by abey79** [comment]
duplicated by https://github.com/rerun-io/rerun/issues/8271
