### ISSUE TITLE
Tracking issue: CI improvements

### ISSUE THREAD

**Issue by jprochazk** [rerun-io/rerun#2776]
- [x] #2827
- [x] https://github.com/rerun-io/rerun/issues/2838
- [x] https://github.com/rerun-io/rerun/issues/2445 (how to avoid CI time explosion?)
- [x] https://github.com/rerun-io/rerun/issues/2511
- [ ] https://github.com/rerun-io/rerun/issues/2607
- [ ] https://github.com/rerun-io/rerun/issues/2648

**Comment by emilk** [comment]
Let's break out the task that are related to speeding up the CI

**Comment by jprochazk** [comment]
> Let's break out the task that are related to speeding up the CI

https://github.com/rerun-io/rerun/issues/3033
