### ISSUE TITLE
Assorted Design Improvements

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#2780]
- [ ] https://github.com/rerun-io/rerun/issues/2726
- [ ] https://github.com/rerun-io/rerun/issues/2727
- [ ] https://github.com/rerun-io/rerun/issues/2728
- [ ] https://github.com/rerun-io/rerun/issues/2729
- [ ] https://github.com/rerun-io/rerun/issues/2730
- [ ] https://github.com/rerun-io/rerun/issues/2731
- [ ] https://github.com/rerun-io/rerun/issues/2732
- [ ] https://github.com/rerun-io/rerun/issues/2732
- [ ] https://github.com/rerun-io/rerun/issues/2734
- [ ] https://github.com/rerun-io/rerun/issues/2735
- [ ] https://github.com/rerun-io/rerun/issues/2736
- [ ] https://github.com/rerun-io/rerun/issues/2737
- [ ] https://github.com/rerun-io/rerun/issues/2738
- [ ] https://github.com/rerun-io/rerun/issues/2724
- [ ] https://github.com/rerun-io/rerun/issues/2709
- [ ] https://github.com/rerun-io/rerun/issues/2701

**Comment by abey79** [comment]
Duplicates #2670
