### ISSUE TITLE
C++ SDK V1

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#2919]
Tracking issue for everything we want to have for a first version of an officially supported C++ SDK.

General guideline:
* **Feature complete**: Log everything that the *new* object oriented Python API can log
* **First class:** Once this ticket is closed we treat it just like our Rust and Python SDK, the same principles for CI, docs, quality etc. apply
* _basic_ distributability - we have an installation guide but it doesn't need to be smooth at this point
*  works on Linux & Mac, Windows optional at this point

----------

Must have:
* [x] feature complete logging
    * #2795
    * #3380
    * https://github.com/rerun-io/rerun/issues/3864
    * [x] #3865
* Docs & Samples
   * [x] #3751
   * [x] #3752
   * [x] #3753
   * [x] #3870
* Code & library quality
   * [x] #2917
   * [x] improve header quality - #2873
   * [x] #2903
   * [x] #2537
 * [x] #3394
 * [x] `log_clear`
 * [x] https://github.com/rerun-io/rerun/issues/3040
 * [x] #3867
 * [x] #3754
 * [x] #3755
 * [x] #3758
 * [x] #3759

Stretch-goals
* [ ] #3139
* [ ] check on distribution size - #2905
* [x] #3757
* [x] #3975
* [x] #3756
* [x] zero copy logging - https://github.com/rerun-io/rerun/issues/3050

Future (i.e. excluded from this release)
* [ ] easy setup
   * [ ] no manual libarrow install etc.
   * [ ] support one or more C++ package manager
* [ ] C++14 support (requiring C++17 so far)
* [ ] #3977
* [ ] Run `just cpp-test` on CI
      * https://github.com/rerun-io/rerun/pull/3921
      * note that we already run all tests, so this isn't critical at all
* [ ] #3976
* [ ] #3868
* [ ] #3974

**Comment by emilk** [comment]
It seems like we should add API docs (generated from docstrings) to this as well

**Comment by Wumpf** [comment]
that's covered by `generate documentation and link from website`
