### ISSUE TITLE
Further upgrade example documentation

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#2932]
Tracking issue for the next set of upgrades to the examples documentation.

- [ ] #2928
- [ ] #2272
- [ ] Unify api examples with bigger examples
- [ ] Use archetypes and api's used in examples as tags to filter on
- [ ] Examples docs shows live web viewer where possible
