### ISSUE TITLE
Tracking issue: Speed up CI

### ISSUE THREAD

**Issue by jprochazk** [rerun-io/rerun#3033]
- [ ] https://github.com/rerun-io/rerun/issues/2762
- [ ] Better job sequencing
      - Cargo rebuilds _a lot_, even with cache during the Rust lints job
- [ ] Speed up web demo build (cache datasets)
- [ ] https://github.com/rerun-io/rerun/issues/2566
- [ ] Parallelize example `.rrd` file generation (?)
- [ ] Attempt to build wheel + WASM in `build web demo` job instead of waiting for those two to finish separately (and reusing their artifacts).
- [ ] Parallelize Rust lints

**Comment by emilk** [comment]
Maybe some tricks can be learned from the CI section of 
https://matklad.github.io/2021/09/04/fast-rust-builds.html

For instance, it suggest setting `CARGO_INCREMENTAL: 0` in our `env` to disable incremental compilation, which should shrink the `/target` folder and maybe improve caching.

A lot of the tricks in https://github.com/rerun-io/rerun/issues/5332 also apply to this
