### ISSUE TITLE
Add "browsing examples" section to the Welcome Screen

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#3096]
The "browsing examples" section is currently missing from the Welcome Screen:

<img width="991" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/82407659-a06c-47af-a53b-09264110e20e">

<img width="1332" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/d5f7fdd7-52f8-467b-a829-e70de6da1c34">

### Goals for the first iteration

- The example list "belongs" to the Welcome Screen (so it's available when the Welcome Screen is, which currently means "as background", when all recordings are closed).
- Example list is built based on a hosted json file containing example metadata.
- Only list examples for which we have a built RRD file (same as with the current [demo.rerun.io](https://demo.rerun.io)).
- Display: simple list of example summaries including title, description, tags, and thumbnail.
- Launching an example triggers downloading the RRD from web.
- While downloading the RRD, the existing "loading screen" shows up.

### Skip for later

- search bar UI
- filter by tag UI
- download progress bar

### TODO

- [x] https://github.com/rerun-io/rerun/issues/3105
- [x] support for launching streams: https://github.com/rerun-io/rerun/issues/2229
- [ ] nice "example card UI"
- [ ] lazy-loaded thumbnails using https://github.com/emilk/egui/issues/3291

**Comment by emilk** [comment]
For the image loading we can use a similar strategy as I used in https://github.com/lampsitter/egui_commonmark/pull/8
That is: a map of Url to `PollPromise<Result<TextureHandle>>`.

At some point I'd like to add proper support for this to egui, and maybe this is the point. `egui` could support a plugin for converting an URI to a `ColorImage`, and then implement the cache for that. For instance:

```rs
trait ImageLoader {
    /// Non-blocking. Returns `Pending` while loading.
    fn load(&self, uri: &str) -> std::task::Poll<Result<ColorImage, String>>;
}
```

Users (like Rerun) can then install an image loader that loads from file or url, etc. This would allow egui to support things like `ui.add(egui::Image::from_uri("foo.png"));`, something users have been asking for for a long time.

We could add `ImageLoaders` for file and web (using ehttp) to the `egui_extras` crate.

I guess it makes sense to add a `Vec<Box<dyn ImageLoader>>` to `epaint::TextureManager`.

This would be good for us, good for `egui_commonmark` (which is good for when we want to integrate markdown into Rerun), and good for the whole egui eco-system.
