### ISSUE TITLE
Tracking Issue: Blueprint Tree UI improvements

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#3120]
## High priority

Workflow:
- [x]  the plus button should use the new "Add SV/Container" modal instead of the old one (it's ok to "loose" the heuristics suggestions for now): https://github.com/rerun-io/rerun/issues/4652
- [x]  support right clicking on items to display a context menu with actions: https://github.com/rerun-io/rerun/issues/4823

Selection improvements
- [ ] make multi-selection compatible with future drag-and-drop and selection panel: https://github.com/rerun-io/rerun/issues/4887
- [ ] introduced "parent selected" state for item that are contained in a parent which is selected: https://github.com/rerun-io/rerun/issues/5257
- [x] #4917
- [ ] select container when clicking in blank space: https://github.com/rerun-io/rerun/issues/4774

Drag and drop improvement:
- [x] reorder with drag and drop:
  - https://github.com/rerun-io/rerun/issues/2652
  - https://github.com/rerun-io/rerun/pull/4910
- [x] Properly deal with the root container: https://github.com/rerun-io/rerun/issues/4909
- [ ] support multi-selection drag-and-drop: https://github.com/rerun-io/rerun/issues/5307
- [x] Improve behaviour for grid container: because of how Grid container work (they support "holes", and tend to swap instead of reflow items when reordering), some drag operation have additional order side effects within the destination (grid) container.

Live-previews:
- [ ] application layer discussion: https://github.com/rerun-io/rerun/issues/4928
- [ ] #4958
- [ ] #4916
- [ ] preview blueprint layout while dragging tiles in the viewport: https://github.com/rerun-io/rerun/issues/3164

--- 

### Design improvement

The end goal is to make the blueprint tree UI contribute positively to the on-boarding experience. Ideally, tt should _teach_ about "stuff", not require prior knowledge to be understood.

- [ ] subdue the label of the container to make it more distinct (_not_ the icon, unless the container is hidden): https://github.com/rerun-io/rerun/pull/4855
- [x] improve the visual distinction between containers, space views, data group and data item
  - Related: #4321
- [ ] A small circle is used as icon for components in the Stream Tree ui. From afar, this looks awfully close to the diamond used for entities, which is confusing.
- [x] #2697
- [ ] https://github.com/rerun-io/rerun/issues/4743 (de-prioritised until a suitable design is available)
- [x] https://github.com/rerun-io/rerun/issues/4964

### Behaviour improvements
- [ ] support drag and drop for data as well
- [ ] When an entity is hovered elsewhere in the UI (selection panel, streams, etc.), the visual feedback is currently to hover the corresponding item(s) in the blueprint tree UI, which is visually very strong. A more toned-done approach might be better.
- [ ]  #2909
- [ ] containers look inactive although they are active
- [ ] hidden elements look inactive although they are active
- [ ] allow unhiding a single child from a hidden (direct or indirect) parent: https://github.com/rerun-io/rerun/issues/3194
- [ ] hiding a container doesn't dim its children
- [x] synchronise hover highlighting between blueprint tree UI and corresponding space view tabs: https://github.com/rerun-io/rerun/issues/1129
- [ ] allow slow click: #2859 
- [ ] allow selection on click down:  #2858

<br/>

Sister issue on Stream Tree UI:
- #3150

**Comment by abey79** [comment]
@nikolausWest I'm tagging this 0.10 for consideration we we prepare that release, as I don't believe anything here is a must for 0.9. Let me know if you feel otherwise, we can break out 0.9-tagged issues as required.

@martenbjork feel free to add to the list, especially if you have clarity on the design part
