### ISSUE TITLE
Streams Panel UI improvements

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#3150]
### Design
- [x] A small circle is used as icon for components. From afar, this looks awfully close to the diamond used for entities in the Blueprint Tree UI, which is confusing.

### Behaviour fix/improvements

- [x] https://github.com/rerun-io/rerun/issues/3152
- [x] https://github.com/rerun-io/rerun/issues/3733

### Timeline fix/improvements

- [ ] #3783 

<br/>

Sister issue on Blueprint Tree UI:
- #3120

**Comment by abey79** [comment]
Closing as not a useful issue
