### ISSUE TITLE
Tracking issue: Revamp of our example building infrastructure

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#3212]
- [x] https://github.com/rerun-io/rerun/pull/3332
- [x] https://github.com/rerun-io/rerun/issues/4489
- [x] https://github.com/rerun-io/rerun/issues/4488
- [x] [Actual nightly builds](https://github.com/rerun-io/rerun/pull/4505)

---

The in-app example page (#3191) relies on pre-build RRD for its example. These RRD must be up-to-date for the dev builds, and version-specific for the public release. These RRD are also costly to build, which means we currently have only 7 examples covered. This figure must be increased.

**Comment by teh-cmc** [comment]
Relevant: https://github.com/rerun-io/rerun/pull/3204 introduces the `_RERUN_TEST_FORCE_SAVE=<filepath.rrd>` environment variable, that will force any `RecordingStream` to write to a specified file on disk, irrelevant of how it was set up (`connect()`, `spawn()`, etc...).

**Comment by emilk** [comment]
Let's try to get this in before 0.9, but start with just the minimal set of examples.

**Comment by emilk** [comment]
The viewer `include_str!`:s `crates/re_viewer/data/examples_manifest.json` which in turn points to `.rrd` urls _at a specific commit_. Currently we need to update `examples_manifest.json` manually.

For 0.9 we could just update it manually to point to .rrd's we've updated specifically for the 0.9 release.

…or we figure out a proper fix for this.
