### ISSUE TITLE
Unify 2D and 3D renderer

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#350]
Currently the 2D view is using egui shapes to do all painting. This makes it difficult to do things like apply colormaps to depth images. We should apply such colormaps in a shader. We also want to be able to display images in 3D views, something we cannot currently do. The solution is to unify the 2D and 3D views.

This issue is about replacing `epaint` with `re_renderer` in the 2D SpaceView (except for text, which we will use `epaint` for).

2D data is just 3D data with Z=0. This means the visualizer view can just put all data into the same Scene3D and paint it using WGPU. If all data is flat, then the default camera is a 2D camera, otherwise the default is a 3D orbit camera.

* [x] #380
* [x] demo 2D view in standalone demo
* [x] make it easy to convert 2D versions of primitives into 3D primitives that `re_renderer` already knows
* [x] Add support for the 2D types to re_renderer
    * [x] #388
    * [x] #389
* [x] Figure out layering/Z-ordering/painters-algorithm for 2D stuff in `re_renderer`
* [x] #382

This is in preparation of #373
