### ISSUE TITLE
0.9 Release checklist

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#3651]
Just before release:
* [x] In various places in the docs and code (e.g. `crates/re_types_builder/src/codegen/docs/mod.rs`) we link to `https://docs.rs/rerun/0.9.0-alpha.6/` and `https://ref.rerun.io/docs/python/HEAD/` but should link to `latest` instead

After release:
* [x] Merge the `update-landing-page` pull request on the landing repository. Make sure the environment variable that points to the commit to use on the rerun repository is set to the latest commit
* [x] Clean up old version of `ref.rerun.io/docs/python` in `gh-pages` branch
* [x] Delete `latest` tag (will be replaced by a branch)
* [x] Delete old python docs links `HEAD`, `test`, `prerelease` (https://github.com/rerun-io/rerun/issues/3647)
