### ISSUE TITLE
Use `pixi` to replace our bash scripts and many of the Dockerfile layers

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#3717]
- https://github.com/rerun-io/rerun/pull/3707 seems very compelling

Pixi should be able to replace all of our current just commands while bringing the added benefit of running things in an environment with managed dependencies. For example, this gives us access to our code-gen dependencies, the `arrow-cpp` we need for building rerun-cpp, etc.

This lets us replace all of the commands in `just` with versions that handle the dep installation first.
This also lets us collapse many of the layers of our Dockerfile into a single `pixi install` invocation.

# TODO
* [x] Use pixi on CI
    * [x] C++: Reopen https://github.com/rerun-io/rerun/pull/3921
* [x] Replace `venv` with pixi
* [x] #4171
* [x] Replace `scripts/requirements-dev.txt` etc
* [x] #4170
* [x] Replace our other `.sh` scripts, if possible (https://prefix.dev/docs/pixi/advanced/advanced_tasks)
* [ ] Publish rerun on pixi
* [ ] …

**Comment by abey79** [comment]
Vaguely relevant issue for me: https://github.com/prefix-dev/pixi/issues/189

**Comment by emilk** [comment]
We should probably keep our `requirements.txt` files, at least most of them (e.g. for examples)

**Comment by Wumpf** [comment]
the only thing we didn't do is to publish rerun on pixi itself, but otherwise we ticked all the boxes now!
