### ISSUE TITLE
Zombie TODOs pass for `0.9.1`

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#3800]
Latest dump:
- [x] ./rerun_py/rerun_sdk/rerun/log_deprecated/transform.py+24: # TODO(#3275): Deprecation notices on these
- [x] ./crates/re_arrow_store/src/store_write.rs+218: // TODO(#1712): That's exactly how one should create a cell of instance keys…
- [x] ./crates/re_log_types/src/data_table.rs+928: // TODO(#1712): This is unnecessarily slow…
- [x] ./crates/re_log_types/src/data_table.rs+1007: // TODO(#1805): Schema metadata gets cloned in every single array.
- [x] ./crates/re_tuid/src/lib.rs+26: // TODO(#1774): shouldn't have to write this manually
