### ISSUE TITLE
0.10 release checklist

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#3962]
# Before the release
* [x] Explain how to download pre-built binaries in
  * [x] `crates/re_viewer/data/quick_start_guides/cpp_connect.md`
  * [x] https://github.com/rerun-io/cpp-example-opencv-eigen
  * [x] example code links in all front matters (https://github.com/rerun-io/rerun/tree/latest/examples/cpp/ etc.):  https://github.com/rerun-io/rerun/pull/4079
  * [x] Make sure install instructions are consistent everywhere for arrow-cpp (C++ Quick Start for instance)
* [x] Port the new cmake-builds-arrow work (https://github.com/rerun-io/cpp-example-opencv-eigen/pull/8) to all our examples, docs, and blog posts
* [x] Merge https://github.com/rerun-io/cpp-example-opencv-eigen/pull/8
* [x] https://github.com/rerun-io/rerun/pull/4077
* [ ] Read through our new C++ docs again
* [x] https://github.com/rerun-io/rerun/pull/4064
* [x] #4066
* [x] Bring https://github.com/rerun-io/landing/pull/506 into a mergable state
* [x] #4076
* [x] Merge https://github.com/rerun-io/rerun/pull/4052
* [x] Collect changelog and write release notes

# Directly after the release
* [x] Update https://github.com/rerun-io/rerun every place that has "C++" as "Coming soon"
   * [x] `README.md`
   * [x] Anywhere with `TODO(#2919)` (https://github.com/rerun-io/rerun/issues/2919)
   * [x] …
* [x] Merge https://github.com/rerun-io/landing/pull/506
* [x] Remove `?speculative-link` from our links (should no longer be needed)
* [ ] Point to https://github.com/rerun-io/rerun/releases/download/0.10.0/rerun_cpp_sdk.zip in …
  * [ ] `crates/re_viewer/data/quick_start_guides/cpp_connect.md`
  * [x] https://github.com/rerun-io/cpp-example-opencv-eigen
  * [ ] example code links in all front matters (https://github.com/rerun-io/rerun/tree/latest/examples/cpp/ etc.)
  * [ ] Make sure install instructions are consistent everywhere for arrow-cpp (C++ Quick Start for instance)
* [x] Find and fix all `TODO(#3962)` 
* [x] Update the "Get started in seconds section" on the landing page
* [x] Update the banner on the landing page to "Read about 0.10, introducing the Rerun SDK for C++"
* [x] Remove link exclusions from [linkinator config](https://github.com/rerun-io/rerun/blob/main/.github/workflows/documentation.yaml#L37)

# Days after the release
* [x] Finish VRS example: https://github.com/rerun-io/cpp-example-vrs/pull/1
* [x] get `rerun` viewer binary on conda
* [ ] get `Rerun C++ SDK` on conda: https://github.com/conda-forge/rerun-sdk-feedstock/issues/18

**Comment by Wumpf** [comment]
Standalone ticket for the last unchecked item:
* #4130
Unlikely to happen immediately. 0.10.0 went fine otherwise!
