### ISSUE TITLE
Blueprint: Query Expressions (backend support)

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#4128]
## Motivation

Our minimal experimental blueprint APIs allow you to explicitly list specific entities to add to a space-view, but this can be quite cumbersome with large scenes. We would like to be able to add an entire sub-tree (or other complex expression) through a single API call.

## Approach

Because the Blueprint needs to be set *before* logging data, there is no way to do this with a mechanism such as a log-time query that resolves to a collection of entity-paths. It must be stored in the blueprint representation as a query which is evaluated at runtime.

Rather than the SpaceViewContents structure used today, which explicitly stores all of the entities within a scene, we will introduce a new "Data Query" concept which evaluates the parts that will be shown in the the space-view *at runtime*.
 - See: [the notion proposal](https://www.notion.so/rerunio/Proposed-Data-Sources-92008f130a7e4e4992f9966cac24ab78) for more details.

## Sub-tasks
 - [x] Implement `DataQuery` trait and wrap `SpaceViewContents` for backwards compatibility.
 - [x] Refactor SpaceView to consume DataResultTree.
 - [x] Replace DataBlueprintGroup with new Property override system that works on DataResultTree.
 - [x] Refactor BlueprintTree to consume DataResultTree.
 - [x] New `DataQuery` implementation to produce DataResultTree from wild-card
 - [ ] ~~MVP Blueprint API for adding `DataQuery` to the blueprint.~~

## Follow-up tasks:
 - https://github.com/rerun-io/rerun/issues/4156
 - https://github.com/rerun-io/rerun/issues/4157
 - https://github.com/rerun-io/rerun/issues/4158

**Comment by jleibs** [comment]
Approach:
 - Keep backwards compatible support when using DataGroup backend in the Blueprint Tree UI
