### ISSUE TITLE
Blueprint-related refactoring

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#4308]
There are several pieces of refactoring that will benefit the ongoing blueprint migration:
- [x] Rename or encapsulate `DataResultTree` -> `QueryResult` and move DataQuery evaluation earlier in the frame:
  - Will be done in: https://github.com/rerun-io/rerun/pull/4310
  - The location is roughly `app_state.rs :: show()` or equivalent. Right before we create `ViewerContext`.
  - All `QueryResult`s will be added to the `ViewerContext`.
  - Invocations of `execute_query` and `resolve` from the `DataQuery` trait are instead replaced by something that looks up the `QueryResult` in the `ViewerContext`.
  - Future: `QueryResult` can be merged with the QueryCache logic.
- [x] Replace SpaceViewContents with DataQuery
  - Will be done in: https://github.com/rerun-io/rerun/pull/4311
  - Everywhere that we use SpaceViewContents needs to use an appropriate QueryResult instead
- [ ] Moved to: https://github.com/rerun-io/rerun/issues/4440
  Refactor blueprint lifecycle, construction and component patterns.
  - Each type: ViewportBlueprint, ContainerBlueprint, SpaceViewBlueprint, DataQueryBlueprint should follow the same design.  They are generally considered to be read-only views of the blueprint on the current frame. They should always store their own `BlueprintId`, which is mappable to an EntityPath used to store any edits. These edits are always deferred through the `CommandSender` and won't be visible until the next frame.  The basic pattern should look like:
    ```
    /// Create a new ephemeral blueprint entity.
    ContainerBlueprint::new() -> ContainerBlueprint;

    /// Send the initial state of an ephemeral blueprint entity to the store
    /// Should never be used on a non-ephemeral blueprint entity such as created via `from_store`
    ContainerBlueprint::save_initial(deferred: &CommandSender);

    /// Remove the entity and all of its children
    /// Note: because blueprint entities aren't stored hierarchically this will generate multiple clear events.
    ContainerBlueprint::clear(deferred: &CommandSender);

    /// Load an actual blueprint component from the store.
    /// Recursively loads all the referenced types.
    ContainerBlueprint::from_store(store: &StoreDb, id: ContainerId) -> ContainerBlueprint {...}

    /// Modify some field.
    /// Used by UI events to modify the blueprint component. Encapsulates all 
    ContainerBlueprint::edit_foo(foo: Foo, deferred: &CommandSender)
    ```
    When this is complete, `sync_viewport_blueprint` should be completely gone.
- [ ] Moved to: https://github.com/rerun-io/rerun/issues/4441
  - Deprecate "groups" as a concept from the `DataResultTree`.
![Image](https://github.com/rerun-io/rerun/assets/3312232/b506a6f3-5cb9-4f7d-a70a-c0fd3ee15ffa) ![Image](https://github.com/rerun-io/rerun/assets/3312232/bd5864fe-8de7-4430-b4cf-50c4ad70913e)
  - Now we have "groups" which map to override-recursive and "entities' which map to override-individual
  - After we will have entities with **two** override paths: "override" and "override_recursive". The UI can then choose which path to use depending on some context of how the override is being set (i.e. a flag for "apply to children")

**Comment by jleibs** [comment]
Closing in favor of new explicit issues.
