### ISSUE TITLE
re_datastore: all around performance pass tracking issue

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#443]
First pass of performance work

- [x] put performance probes everywhere
- [x] provide helpers to gather detailed metrics: global, per-table, per-table-per-bucket
- [x] a lot superfluous clones & copies that need to go away asap
- [x] need integration benchmark suites
   - [x] write path, read path, write+read path

The end game, of course, is that query results from the datastore should _always be_ references to the stored data.

And all of the following:
- [x] #433
- [x] #442
- [x] #451
- [x] #453
- [x] #529 

Optional:
- [x] #448
