### ISSUE TITLE
Tracking issue: dataframe view

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#4466]
[**See all issues**](https://github.com/rerun-io/rerun/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+label%3Afeat-dataframe-view)

#### Time query interaction features

- [x] https://github.com/rerun-io/rerun/issues/7065
- [x] #7130
- As a user I want to be able to:
  - [x] Switch between active timeline and 'local to the table view' timeline any time. 
  - [x] Choose how do I want to see my data view locally: latest at or within a time range. And be able to switch between them:  #6869 
  - [x] introduce a quick filter for –∞ to +∞
  - [x] smooth transition between selections, i.e. when switching from lates at N to time range, keep time range similar to the N values.

#### Displaying and grouping data values in a table (archetypes and batches)

- [x] https://github.com/rerun-io/rerun/issues/7066
- As a user I want to be able to:
  - [ ] easily see which components are related to each other in an archetype hierarchy (group columns by archetype)
  - [ ] easily see if a given entity has a instance batch (display the batch instance indicator: either within an archetype or as a separate column)
  - [x] expand and collapse the batch to see values per each entity

#### Viewing the data in the table
- [ ] https://github.com/rerun-io/rerun/issues/7068
- [x] https://github.com/rerun-io/rerun/issues/7067
- [x] https://github.com/rerun-io/rerun/issues/7069
- [ ] https://github.com/rerun-io/rerun/issues/7070
- As a user I want to be able to:
  - [ ] decide which components I see (aka show/hide column)
  - [ ] see my data organized by entity OR by time log (user can choose between only when looking at a range query)
  - [ ] sort/reorder the entities and timelog columns (ascending/descending)
  - [ ] easily scan which entities belong to the same time stamp (or vice versa depending on what is leading). Joined and sticky cell value. 
  - [ ] always see which component I am looking at when scrolling (sticky headers)

#### Cosmetics
- [ ] initial columns size are usually bad
- [ ] when in a time range : add color to the first column background
- [ ] when header has archetypes and components: use a different separators for between components belonging to the same archetype. 
- [ ] change shades of grey for: alternating background of rows, the separators, fonts (including headers, entities, time logs, all other values)

#### Other features
- [x] https://github.com/rerun-io/rerun/issues/6896
- Improve the experience when interacting with a dataframe view and a spatial view side-by-side:
  - [x] Autoscroll on an instance in the latest at table when clicked in 2d/3d view.
  - [x] Autoscroll on an entity in the range table when selected elsewhere—if entity are the primary key!
  - [ ] https://github.com/rerun-io/rerun/issues/5382
  - [ ] https://github.com/rerun-io/rerun/issues/5257
- View configuration and properties
- [x] https://github.com/rerun-io/rerun/issues/6910
- [ ] https://github.com/rerun-io/rerun/issues/6913
- [ ] In "latest at" mode: "Last Updated" somewhere for each cell
- [ ] Export table to CSV

#### Usability helper
- [ ] Split view per entity: with many entities, the dataframe might quickly become unwieldy. This feature would create multiple, tabbed views with the exact same configuration, but each with a single entity set as filter. // not sure about this one (Katya)

#### Bugs/usability issue

- [x] proper space view icon
- [ ] properly handle `ClearComponents`
- [x] heuristics shouldn't suggest dataframe space views?
- [x] many `data_ui::ui` function allow wrapping -> specific `UiVerbosity`? 

#### Random question/exploration

- Should we have a temporal view where the rows are time sample defined by the users? aka each row is a latest at query, for ti=x0 + i * dx?

Design documents:
- https://www.figma.com/board/vvJts8ljILItsWXDgB9mnK/Table-View-Data-browser?node-id=0-1&t=Bo3r4nojxRNi4g3G-1
- https://www.notion.so/rerunio/Data-Browser-25e397d32f0d45489f1fb35b3bb28a60?pvs=4

**Comment by Wumpf** [comment]
It's not unlikely that we add some form of CSV support there as we go, but CSV is a quite opinionated and not well specified format (different locales may use . or , for decimal separators causing all sort of issues, different loaders allow all sort of column separation characters etc.), so this is probably best served with a custom data loader - already today you could easily write one that reads in a csv to a markdown and logs into Rerun or into a text log). Naturally, none of these representations is feature-wise all that great; for that I think we'd really need the feature described in this ticket.
To learn more about custom data loaders check the docs [here](https://www.rerun.io/docs/howto/open-any-file#adding-support-for-arbitrary-filetypes) and/or the respective examples, here's [the python one](https://github.com/rerun-io/rerun/tree/main/examples/python/external_data_loader).

**Comment by gavrelina** [comment]
Updated some parts of the ticket based on design explorations documented here: https://github.com/rerun-io/rerun/issues/6957

**Comment by nikolausWest** [comment]
This issue seems to not be kept up to date (some of the unchecked boxes I believe are actually implemented). @abey79 should this be closed in favor of a new tracking issue?

**Comment by abey79** [comment]
I agree this is a bit all over the place and is not an actual representation of current priorities. Let's close this and reopen project-style issues as short term priorities are clarified.
