### ISSUE TITLE
New container/space view addition workflow

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#4492]
This issue is about completing the design and implementation of the new container/space view addition workflow, including:

#### Design

- [ ] Design the "Add SV/container" modal
- [ ] Work out the workflow from "click the add button in blueprint tree" to "adding stuff with the modal in the selection panel"

#### Implementation

- [ ] Container's selection panel should display children (either container or SV)
- [ ] Container's selection panel should have an "add" button
- [ ] Implement that  "Add SV/Container" modal.
- [ ] The "add" button in the blueprint tree should forward to this workflow instead of having its own popup menu.

cc @martenbjork
