### ISSUE TITLE
Rerun 0.12 zombie TODO pass

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#4498]
- [x] ./crates/re_viewer/src/ui/welcome_screen/welcome_page.rs+14: const CPP_SPAWN_MARKDOWN: &str = include_str!("../../../data/quick_start_guides/cpp_connect.md"); // TODO(#3757)
- [x] ./crates/re_viewer/src/ui/welcome_screen/welcome_page.rs+28: include_str!("../../../data/quick_start_guides/quick_start_connect.cpp"); // TODO(#3757)
- [x] ./crates/re_arrow_store/src/store_write.rs+228: // TODO(#1777): shared slices for auto generated keys
- [x] ./crates/re_data_store/src/entity_properties.rs+80: // TODO(#1423): We need to properly split entity properties that only apply to specific
- [x] ./rerun_cpp/src/rerun/collection.hpp+30: ///         TODO(#3794): don't do std::vector
- [x] ./rerun_cpp/src/rerun/collection.hpp+277: /// TODO(#4225): So far it always is continuous, but in the future we want to support strides!
- [x] ./rerun_cpp/src/rerun/archetypes/boxes3d.hpp+118: /// TODO(#3794): This should not take an std::vector.
- [x] ./rerun_cpp/src/rerun/archetypes/boxes3d.hpp+126: /// TODO(#3794): This should not take an std::vector.
- [x] ./rerun_cpp/src/rerun/archetypes/boxes3d.hpp+140: /// TODO(#3794): This should not take an std::vector.
- [x] ./rerun_cpp/src/rerun/archetypes/boxes3d_ext.cpp+34: /// TODO(#3794): This should not take an std::vector.
- [x] ./rerun_cpp/src/rerun/archetypes/boxes3d_ext.cpp+42: /// TODO(#3794): This should not take an std::vector.
- [x] ./rerun_cpp/src/rerun/archetypes/boxes3d_ext.cpp+56: /// TODO(#3794): This should not take an std::vector.
- [x] ./rerun_cpp/docs/readme_snippets.cpp+14: // TODO(#3794): Once image logging is nicer, we should do that in this snippet as well!
- [x] ./rerun_cpp/docs/writing_docs.md+14: TODO(#3974): get this part working for C++!
- [x] ./rerun_cpp/tests/recording_stream.cpp+131: // TODO(#2889): Setting thread locals causes a crash on shutdown on macOS.
- [x] ./docs/code-examples/roundtrips.py+29: "quick_start_spawn": ["cpp"], # TODO(#3870): Not yet implemented in C++
- [x] ./docs/content/reference/viewer/blueprint.md+43: [TODO(#1174)](https://github.com/rerun-io/rerun/issues/1174): Editable & user defined Data Blueprint Groups
- [x] ./tests/python/gc_stress/many_large_single_row_recordings.py+30: # TODO(#4183): Investigate this.
