### ISSUE TITLE
Tracking Issue: Add SpaceView/Container workflow

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#4825]
## High priority (Late January 2024 cycle)

- [x] close modal on click (one can only add a single item per opening of the modal): https://github.com/rerun-io/rerun/pull/4927
- [x] remove the big plus button: https://github.com/rerun-io/rerun/pull/4927
- [ ] #5011
- [ ] #4929
- [ ] preview the result of adding the thing that is being selected: https://github.com/rerun-io/rerun/issues/4928
- [x] disable "same-type" container types in the modal (adding vertical container to a vertical container is a no-op due to simplification)

---

## Kitchen sink

- …

**Comment by abey79** [comment]
not a useful issue
