### ISSUE TITLE
Transform Hierarchy available to space views

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#525]
* use transform hierarchy to show 2d/3d data in the right context to each other (where right now we only can show either 2d or 3d data)
    * furthermore, apply the tree of transforms so a deep hierarchy can be shown in a single view where right now we 
can only create space views at leaves that don't have any transform
* Hover in one space view, there is an indication of correspondence in the any other space that you can get through the transform hierarchy.
* Data is available to show through transforms in respective space views
   * refine heuristics on what to show on autopopulate -- much more data is available now for each view, we might need to be selective (experiment!)

Note there is two kinds of correspondences we need to visualize through all these things:
* object correspondence (point selected in one view, highlights the *same* point in all other views that show it)
* coordinate correspondence (pixel hovered -> ray in space)

Prerequisites:
* [x] #373 
* build up a transform hierarchy resolver (& cache like thing?)
   * for a given object it needs to be fast to get the accumulated transform given its object hierarchy
   * establish `space -> world -> view -> projection`
* Lines and Points probably need to bite the bullet and do a multi-draw call setup to bundle by shared space->world transform
  * [x] #509 will need to have a concept of groupings with same transform
  * [x] linesstrips need to be grouped to have the same transform

Cross 2D/3D:
* [x] #399 
* [x] #348

Apply transform hierarchy:
* [ ] #349 
* [x] #375
* [x] Automatically project 3D -> 3D from parent to child space

Emerging / related issues:
* [ ] #398 (Every spaceview has everything available? Overview?)
* [x] #510 (think through again how much this makes sense given what a user can log!)
