### ISSUE TITLE
Summary issue: things that are broken or annoying on the Stable Diffusion example

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#556]
### Context
I'm currently working on an example of using Rerun to dig into Stable Diffusion. Particularly around [this implementation](https://github.com/apple/ml-stable-diffusion) from Apple. To better understand what's going on it can be helpfull to read through [this guide on Stable Diffusion](https://jalammar.github.io/illustrated-stable-diffusion/).

### Overview
I've added a bunch of logs (mostly tensors) to the original script. Here is a screenshot of how the UI looks by default:
<img width="1488" alt="Screenshot 2022-12-14 at 17 06 40" src="https://user-images.githubusercontent.com/2624717/207649822-c9012c6e-3ba3-4f1f-be91-c1cfa2e44d91.png">

[Here is the rrd file](https://drive.google.com/file/d/1d8baSjNxqBHyedbf9jTlsLp5YfNScLMA/view?usp=sharing).

#### SDK

- [x] Doesn't accept all numerical types for tensors. In this example that was a problem for float16 and u64, which resulted in exceptions.
  - https://github.com/rerun-io/rerun/pull/608
- [x] Raises exceptions when the number of tensor names don't match the number of dimensions for a tensor
- [x] Raises exceptions when the user passes in data of the wrong type (for instance a list of dict when a tensor or string was expected). Related: as a python developer using someone else's libraries, I generally won't know what type of data I have. Being able to "just log it" is a major value add.
- [ ] log_image raises and exception if you pass it a numpy array with an extra dimension (for a single batch). For instance shape like [1, height, width, 3] 

#### Viewer

- [x] Heuristics create space views at the wrong level for tensors. This results in space views with more than one tensor, which can't be displayed.
- [x] #557
- [x] Viewer incorrectly interprets some tensors as images

#### Viewer

- [x] Lot's of wasted space for small tensors. One option would be to support having several tensors in the same view to create a tighter layout. It's a little unclear what the (coordinate) becomes then though.
- [x] Slice selector takes up a lot of space in the tensor views
- [ ] Lack of sub-timelines. I want to look at all the data oriented along the "step" timeline but some important things got logged before it's creation. I would like them all to just show up as "before step 0".
- [x] The toggle buttons on the blueprints are a bit small and it's not obvious they stand for toggling visibility.
- [ ] Data ranges (used for coloring) of tensors are recomputed (and can't be changed manually) per event, which makes comparing tensors over time difficult.
- [x] I find it very hard to zoom and navigate in the streams view
  - https://github.com/rerun-io/rerun/pull/606
- [ ] Removing a view from the viewport also runs some version of "Auto-populate Viewport"  
- [ ] Can't group several space views behind a tab. I would for instance like to put all visualizations describing the variational auto encoder behind a single tab.
- [x] Hard to see depth in depth images with the grayscale
- [ ] Viewer sometimes interprets tensors as images. Would like to be able to choose if a tensor is interpreted as an image or general tensor when the heuristics gets it wrong 

#### SDK

- [ ] #631

#### Viewer

- [x] A way to remove data blueprints
- [ ] Hover inspection for tensors
- [ ] The ability to see and edit the layout structure (i.e. containers) in the blueprint. Matters a lot for complex layouts.

### Related issues
* https://github.com/rerun-io/rerun/issues/531
