### ISSUE TITLE
Blueprintify Space View properties

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#6083]
Formalizing the data structure of various space view blueprints and make them accessible from ui and code

* General
   * [x] Visual time Range
        * we may handle this special - as a default property rather than a space view property
        * related to #4953

* Spatial views
   * [ ] 3D eye camera
   * [ ] 2D canvas. related to
       * #2663
       * #2531
       * #6247
    * [x] https://github.com/rerun-io/rerun/issues/6113
    * [x] origin axis is going to be obsolete once arbitrary visualizers can be enabled everywhere  - since the new `AxisThree` doesn't have any required components, it can be enabled everywhere
* Tensor
   * [x] colormap https://github.com/rerun-io/rerun/pull/6585
   * [x] texture filter https://github.com/rerun-io/rerun/pull/6585
   * [x] Slice selection, orientation https://github.com/rerun-io/rerun/pull/6590
* TimeSeries & BarChart
  * [ ] TimeSeries / BarChart plot orientation (similar to 2D canvas). Related to:
      * #5075
  * [ ] #4818 
* Log View https://github.com/rerun-io/rerun/issues/6824

List almost certainly incomplete!

**Comment by Wumpf** [comment]
Closed in favor of new tracking issue
* https://github.com/rerun-io/rerun/issues/6826
