### ISSUE TITLE
Improvements to the RRD CLI tool

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#7048]
- [x] Refactor everything out of the gigantic `run.rs`
- [x] Implement support for stdio streaming (`rerun rrd merge rec1.rrd rec2.rrd | rerun rrd compact`) 
- [x] Implement support for wildcards (`rerun rrd merge *.rrd -o all_my_recordings.rrd`)
- [x] Expose compaction settings via CLI flags too for better UX (`rerun rrd compact --chunk-max-rows 9999 ...`)
- [x] Implement support for dropping timelines (`rerun rrd drop --timeline "log_time"`)
- [x] Support multi-recording rrd files in all commands
- [ ] `rerun rrd print` should have verbosity levels, and only show metadata at verbosity zero
- [x] parallel input/output
- [ ] Put the CLI autogenerated docs in `Reference` on the website

**Comment by emilk** [comment]
In the interest of getting 0.18 out the door this cycle, we'll just document that the RRD CLI is half-baked and will likely change
