### ISSUE TITLE
Release 0.18

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#7052]
# TODO
* [x] Document what components can and cannot be batch-logged (https://github.com/rerun-io/rerun/issues/6592)
* [x] Write changelog
* [x] Giga check: checklist, snippets, examples
* [x] Update roadmap
* [x] https://github.com/rerun-io/rerun/pull/7198
