### ISSUE TITLE
Improved Camera Frustum handling

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#706]
Cameras behave oddly right now!

* [x] They don't have any representation in list of data blue prints in the blueprint panel
* [x] https://github.com/rerun-io/rerun/issues/681
* [x] https://github.com/rerun-io/rerun/issues/638
* [x] https://github.com/rerun-io/rerun/issues/682
* [x] https://github.com/rerun-io/rerun/issues/686
* [x] https://github.com/rerun-io/rerun/issues/693
* [x] #731
