### ISSUE TITLE
Native AV1 decoding via `rav1d/dav1d`

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#7605]
* Part of #7298

# Progress
Experimental support using rav1d can be found in:
* https://github.com/rerun-io/rerun/pull/7557

## TODO
* [x] https://github.com/rerun-io/rerun/pull/7563 (required by [rav1d](https://crates.io/crates/rav1d))
* [x] https://github.com/rerun-io/rerun/pull/7557
* [x] Publish [our own `rav1d` fork](https://github.com/rerun-io/rav1d) as `re_rav1d` with:
  * https://github.com/memorysafety/rav1d/pull/1362
  * https://github.com/memorysafety/rav1d/pull/1364
* [x] [Use a write-belt for the texture upload (instead of raw `wgpu::Queue`)](https://github.com/rerun-io/rerun/pull/7557#discussion_r1787480232)
* [x] https://github.com/rerun-io/rerun/issues/7608
* [ ] Check memory use
* [x] https://github.com/rerun-io/rerun/issues/7662 Update the video support matrix docs
