### ISSUE TITLE
Releasable MVP for the Map view

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#7877]
Initial PR: #6561 

**Absolute "must" for the first release**:
- [x] Visible time range
- [x] https://github.com/rerun-io/rerun/issues/7849
- [x] Interactive entities: selectable and hover tooltip (blocked on https://github.com/podusowski/walkers/issues/197)
  - https://github.com/rerun-io/rerun/pull/7938
- [x] https://github.com/podusowski/walkers/pull/221
- [x] https://github.com/rerun-io/rerun/issues/7937
- [x] https://github.com/rerun-io/rerun/pull/7972
- [x] bp api + snippet/screenshot: https://github.com/rerun-io/rerun/pull/8027
- [x] https://github.com/rerun-io/rerun/issues/7872
  - https://github.com/rerun-io/rerun/pull/8015
- [x] #7968
- [x] docs: https://github.com/rerun-io/rerun/pull/8084
- [x] Update nuscene example: #8034
- [x] How-to guide: very simple, mostly for discoverability: https://github.com/rerun-io/rerun/pull/8075
- [x] Basic geoXXX example that is included in the viewer: https://github.com/rerun-io/rerun/pull/8044
- [x] https://github.com/rerun-io/rerun/issues/8032
  - https://github.com/rerun-io/rerun/pull/8055
- [x] https://github.com/rerun-io/rerun/pull/8078
- [x] https://github.com/rerun-io/rerun/issues/8052

**OK not to have for the first release**:
- [ ] https://github.com/rerun-io/rerun/issues/8077
- [ ] dogfood: update the air traffic data example to use the map view
- [ ] #8086
- [ ] https://github.com/rerun-io/rerun/issues/7963
- [ ] #8067
- [ ] https://github.com/rerun-io/rerun/issues/7876
- [ ] #8066
- [ ] #8068
- [ ] #8087
- [ ] #8089
- [ ] #8090

**Comment by gavrelina** [comment]
thoughts and ideas! 
- https://github.com/podusowski/walkers/issues/210 add support to pan with the trackpad
- allow for transparency of the point styles (within a map context the layer of map actually has important information, so it's great to allow users flexibility to peek it once they need it)
- think of a seamless and easy flow to add mapbox API keys 
- I'd propose to change the default style of dots to have some kind of tiny shadow under, because maps are usually very busy with lots of colors and signs already, and now the dots are easily blending in with the rest. so would be cool to think how can we can make it standing out better by default. not urgent, but a nice improvement with time. 
- I can also imagine that being able to define different symbols and not only dots would come in handy.
- and a legend! 
- and adding labels! 

(okay I will stop here, I think the #1 is the prio, then the API key flow, and the rest can be added as we go)

**Comment by Wumpf** [comment]
everything in the must-have list got done!
