### ISSUE TITLE
Make visualizers & archetypes map 1:1 (+notes on visualizer selection in world without indicators)

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#8368]
## Today
- Visualizer identifiers are distinct from archetype names
    - but **most** of the time identical
- Visualizers are selected heuristically based on archetype indicators
- Visualizers can be set explicitly via `VisualizerOverrides`

### Points of friction

- visualizers are a separate and under-documented concept
- `VisualizerOverrides` has informal list of visualizer strings that is not kept up to date and doesn't show up anywhere else
- tagged components go away - how to decide visualizer when names are conflicting?

## Solution: correlation of archetypes & visualizers

Each visualizer can be described by a name & a list of components, i.e. they _are_ archetypes already.

-> Some archetypes don't have a visualizer - e.g. `Scalar`
-> Separate “required for logging” & “required for visualizing” - `Scalar` is required to visualize point/line, so we won't offer it automatically. But logging `SeriesLine` doesn't require `Scalar` and the presence of its tag still brings the visualizer into existence.

Going forward, some archetypes may have to be split up:
There can be a "base" archetype for mesh data and additional components in a `MeshWireframe`
Note that the base archetype is typically the "raw data" and may be standardized in sorbet much earlier, whereas the extending "visualizer archetype" may follow later.

We likely want some kind of codegen supported ‘extends’ construct to better express this, _potentially_ with specially generated code & docs.

## Setting visualizers

`VisualizerOverrides` 's possible values are any archetype name which is visualizable.

Default heuristic for enabling visualizers is governed by the presence of any matching archetype name in any tag on a given entity.
A store subscriber gathers this data → replaces “indicated component concept”

Beyond that there can still be arbitrary heuristics that for instance ensure that a `Scalar` is shown with `SeriesPoint`

## TODOs

* [ ] Remove visualizer identifiers and replace them with archetype names
* [ ] Adjust docs & functionality `VisualizerOverrides` accordingly
* [ ] remove `VisualizerSystem::visualizer_query_info` as it is fully governed by the matching archetype definition
     * [ ] split concept of "requried for visualizing" & "required for logging", add `Scalar` to `SeriesPoint` & `SeriesLine` accordingly
* [ ] (upon removal of indicators:) change indicated entities to look for any archetype name being set
* [ ] Ensure docs reflect all of the above

## Future work

- `Transform3D` should probably split out `TransformArrows3D` which is a different visualizer. How to make it easy to set this on an existing `Transform3D` (Short term: rename the visualizer), are the ergonomics of this fine?
- Is there a more generic concept of tag overrides? (instead of `VisualizerOverrides`)
- do we still need explicit indicator-like thing in some places to easily enable visualizers
    - conceptually: entity path + tag should just work
    - some kind of new static data?

---

Full internal meeting notes this is based on:
https://www.notion.so/rerunio/Visualizers-tagged-components-157b24554b1980e2950fdc88d9e9a7d4
