### ISSUE TITLE
Optimize point clouds

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#850]
In the nyud example, `SceneSpatial::load_objects` goes from 8.5ms to 16ms.

Classic:
![Screen Shot 2023-01-20 at 14 12 56](https://user-images.githubusercontent.com/1148717/213703732-c5058a57-9f4d-4a6a-b5e3-450d0387a581.png)

Arrow:
![Screen Shot 2023-01-20 at 14 23 48](https://user-images.githubusercontent.com/1148717/213705222-aa94b026-e385-487c-91ff-4b9335544d10.png)

## TODO:
* [ ] Improve `crates/re_query/benches/query_benchmark.rs` with benchmarks of:
   * [x] full primary and full secondary
   * [ ] full primary and sparse secondary
   * [ ] full primary and splat secondary
   * [ ] full primary and missing secondary
* [ ] Realistic point cloud benchmark, similar to nyud and/or colmap, using actual `Points3DPart::load`
* [ ] Write tests for `ComponentJoinedIterator`:
   * [ ] full primary and full secondary
   * [ ] full primary and sparse secondary
   * [ ] full primary and splat secondary
   * [ ] full primary and missing secondary
* [ ] Optimize `ComponentJoinedIterator`:
  - Special case for the common case when the instance keys are identical
    (no need to compare them - if they are same length, and starts and end on the same key, with the length as the difference, then they are the same)

**Comment by emilk** [comment]
* Closing in favor of https://github.com/rerun-io/rerun/issues/1136
