### ISSUE TITLE
Main-site documentation ready for launch

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#949]
Good reference on writing docs: https://documentation.divio.com/

Tracking issue for doc pages that still need writing/cleanup:
 - [x] Splash image for documentation landing page
 - [ ] https://github.com/rerun-io/rerun/issues/971
 - [ ] https://github.com/rerun-io/rerun/issues/1042
 - [x] https://github.com/rerun-io/rerun/issues/972
 - [x] https://github.com/rerun-io/rerun/issues/973
 - [x] https://github.com/rerun-io/rerun/issues/1043
 - [x] https://github.com/rerun-io/rerun/issues/1044
 - [x] https://github.com/rerun-io/rerun/issues/1045
 - [ ] ~https://github.com/rerun-io/rerun/issues/1046~
 - [x] https://github.com/rerun-io/rerun/issues/1047
 - [x] https://github.com/rerun-io/rerun/issues/1048
 - [x] https://github.com/rerun-io/rerun/issues/1049
